server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/hanium
    username: ym
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true #spring boot 2.4 or 2.5???? ?? ?? ?? ?? test? db ???? ?? ? ??
    hibernate.ddl-auto: update
    open-in-view: false
    show-sql: true  #?? ????
    properties: #jpa ???? ?? ??? ????? ?? ? ?? ?? spring? ?????? ?? ???? ?? ???? ?? ????
      hibernate.format_sql: true #??? ??? ?? ???? ??? ? ? ?? ??
      hibernate.default_batch_fetch_size: 100 #jpa?? ????? ??? ??? ?? ? ??? ??? ? ??? ???
  elasticsearch:
    cluster:
      initial-master-nodes: ip-172-31-43-166
    uris: http://3.36.169.149:9200

  #spring.datasource:
  #  #hikari.maximum-pool-size: 4
  #  url: jdbc:postgresql://localhost:32769/mysns
  #  username: postgres
  #  password: postgres
  #  platform: postgres
  #  driver-class-name: org.postgresql.Driver

#  spring.datasource:
#    #hikari.maximum-pool-size: 4
#    url: jdbc:postgresql://db:5432/appdb
#    username: postgres
#    password: example
#    platform: postgres
#    driver-class-name: org.postgresql.Driver
#spring:
#  sql:
#    init:
#      mode: always
jwt:
  key: Hanium_PROJ_APPLICATION-2022.key
  token.expired-time-ms: 2592000000