
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_shop?serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace